baseurl = "/"
languageCode = "en-us"
title = "Introduction to Probability and Statistics at Reed College"
theme = "hugo-xmin"
googleAnalytics = ""
disqusShortname = ""
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2
[[menu.main]]
    name = "Syllabus"
    url = "/syllabus/"
    weight = 3
[[menu.main]]
    name = "Labs"
    url = "/labs/"
    weight = 4

[params]
    description = "Introduction to Probability and Statistics At Reed College"
    footer = "&copy; [Andrew Bray](https://andrewpbray.github.io/) 2018 | [Github](https://andrewpbray.github.io/) "
